# config.yaml
baseURL: https://monsterspotting.netlify.app
languageCode: en-us
title: Monsterspotting
paginate: 10
caches:
  getresource:
    maxAge: 0
module:
  mounts:
  - source: content
    target: content
  - source: prebuild/public/monster
    target: content/monster